### ISSUE TITLE
(1.21.5) Visual artifacting when rain occurs with the mod Particle Rain

### ISSUE THREAD

**Issue by STRYTUS** [Qendolin/better-clouds#197]
The mod was working fine and all until the weather gets to rainy, rejoined the world its fixed but soon artifacting happens again. Deduced it to be compability with the mod [Particle Rain](https://modrinth.com/mod/particle-rain)
After a while it disappears by itself, I believe it happens more often near where chunk arent loaded? (not sure)

At night
![Image](https://github.com/user-attachments/assets/64b7db87-f05a-4cd1-9875-ab7fa3b8a17e)
At day
![Image](https://github.com/user-attachments/assets/e6286367-651c-4967-85fe-1156af96b0f3)
Doesnt disappear when the weather is cleared up but after a while it fixes itself
![Image](https://github.com/user-attachments/assets/14306056-9afe-4c7e-800b-aee7ab66270e)
How it looks after it fixes itself (Normal)
![Image](https://github.com/user-attachments/assets/a0a13d2f-ae19-4740-a39a-e7c5c2d0dece)
Video Example
https://github.com/user-attachments/assets/278a5d03-38d6-406e-8afd-3afc174b3965

Mod Version:  1.21.5 Fabric
OS: Windows
Shader:  BSL

**Comment by Qendolin** [comment]
I'm going to have to take a closer look, but from what I know setting the graphics quality in your video settings to Fabulous should fix this.

**Comment by STRYTUS** [comment]
Hmm not sure how to do that since I already have everything on Fancy with Sodium, that's already the highest options, I already have all other options in the graphics category turned on and also tried all BSL quality presets.

Tried changing shaders and the clouds preset too with ComplementaryReimagined and Solas, problem persists too

**Comment by Qendolin** [comment]
I can reproduce this issue, gonna take some time to fix.

**Comment by Qendolin** [comment]
For got to say this here: This should be fixed on the new 1.21.5 beta release

**Comment by devjacjef** [comment]
~~hey guys, i am also experiencing this issue.~~

~~Currently using a list of different mods, unsure which one might be conflicting~~

~~- Fog~~
~~- Better Clouds~~
~~- Iris~~



~~On Version 1.21.5 and using version v1.9.2+1.21.5-fabric.~~

Never mind, all works just fine! What a beautiful mod.
