### ISSUE TITLE
Crash when jumping into water

### ISSUE THREAD

**Issue by MagmaBro123** [Qendolin/better-clouds#30]
## Description
Title.

### System Environment
- GPU:
![image](https://github.com/Qendolin/better-clouds/assets/51277766/e614fb82-028c-4526-bc4f-69a9a160e50e)
- Mod Version: better-clouds-1.2.2-BETA+1.20.1.12a1b70
- OS: Windows 10.

*Optional:*
- Shader Pack: None.
- Other Mods: Tested with and without other mods, same issues.

### Game Log / Crash Report
[2023-06-27-4.log](https://github.com/Qendolin/better-clouds/files/11890505/2023-06-27-4.log)
(The "odd" one)
[hs_err_pid14120.log](https://github.com/Qendolin/better-clouds/files/11890509/hs_err_pid14120.log)

**Comment by Qendolin** [comment]
The issue seems to be caused by diving into water, and is probably not better clouds's fault

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.3.1+1.20.1-B

**Comment by MagmaBro123** [comment]
Huh. Thought the odd reports I gave would cause issues for you, thanks so much!

**Comment by Qendolin** [comment]
@MagmaBro123  you should set up a whitelist on your server, just saying

**Comment by MagmaBro123** [comment]
@Qendolin It seems this issue is still happening.

[crash-2023-07-02_10.46.32-client.txt](https://github.com/Qendolin/better-clouds/files/11930110/crash-2023-07-02_10.46.32-client.txt)

**Comment by Qendolin** [comment]
That crash seems to be caused by extended clouds.
Reference:
```
Caused by: java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:184) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:173) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.enableCull(RenderSystem.java:381) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.handler$chm000$moreculling$renderClouds(class_761.java:10465) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3239(class_761.java) ~[client-intermediary.jar:?]
	**at net.minecraft.class_761.mdd1c79c$extendedclouds$lambda$renderClouds$1$4(class_761.java:5550) ~[client-intermediary.jar:?]**
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by MagmaBro123** [comment]
Huh... You should probably add compatibility with it, unless this mod already does something similar.

**Comment by Qendolin** [comment]
Better clouds already allows you to extend the distance at which clouds render. In the config the option is called "Distance".

**Comment by MagmaBro123** [comment]
Ah, my bad then. Reported this to them, will remove it. Sorry lol.
